/**
 * Generate watermark text for exports
 * This is a critical anti-churn mechanism
 */
export function generateWatermark(exportType: 'snapshot' | 'subscription' | 'admin'): string {
  const brandName = 'Business Intelligence Pro'; // Replace with your brand
  const snapshotDate = new Date().toISOString().split('T')[0];
  
  if (exportType === 'snapshot') {
    return `Generated by ${brandName}\nSnapshot date: ${snapshotDate}\nData may be outdated. This is a frozen snapshot.`;
  }
  
  return `Generated by ${brandName}\nExport date: ${snapshotDate}\nData may be outdated. For fresh data, use our platform.`;
}

/**
 * Generate footer text for Excel exports
 */
export function generateFooterText(exportType: 'snapshot' | 'subscription' | 'admin'): string {
  const watermark = generateWatermark(exportType);
  return watermark.replace(/\n/g, ' | ');
}
